### ISSUE TITLE
Can you please explain the data in "article_full.json" file?

### ISSUE THREAD

**Issue by shamanez** [salesforce/QAConv#2]
I want to use the dataset in "full-mode" and I am trying to create the knowledgebase.  So could you please let me know which JSON file I should use? 

Also please let me know what are "newsdial-XXX" and  "openslack-62" names?

**Comment by jasonwu0731** [comment]
Hi @shamanez,

There are two files, one is article_segment.json and one is article_full.json. The former is our segmented version (describe in paper section 2.1.1) and the latter is the whole dialogue.

If you want to follow our settings to build the KB, please check [this file](https://github.com/salesforce/QAConv/blob/master/retriever/bm25.py) and this function [get_chunks_by_qa](https://github.com/salesforce/QAConv/blob/master/retriever/utils.py) as an example.

**Comment by shamanez** [comment]
Thanks for the prompt reply. But in the paper, you have evaluated the model on full mode that consist of a retrival phase.  In that section you have mentioned the retrieval was done using sub-sections of KB , rather than whole thing (with the given set of assumptions). I am asking for that KB file.

Since you have used a DPR, what did you use as the title of the passage ? 


The last one, I am working around the article_fill.json.  In this file there are key names like  **court-03-1693**.  So can you please tell whether this is the specific ID go entire conversation ?

**Comment by jasonwu0731** [comment]
Hi @shamanez,

1. article_segment.json contains all the chunks that we split and collect the QA samples. It is a subset of article_full.json, where the keys and values are the whole IDs and conversations we obtained from the original source.
2. They are unique keys for all the conversations we used and they can be used to index the DPR model. I am not quite sure what do you mean by "Title", the keys are just the dataset name + some of their original indexing or meta information.

**Comment by shamanez** [comment]
Hi, thanks a lot for the clarification. I think I got the answer. What I meant by title is,  usually, when we indexing a KB with DPR, we append the title of the main document to the passage. So here, I guess I can use the "key" as meta information.
