### ISSUE TITLE
What is the model you have used to summarize conversations ?

### ISSUE THREAD

**Issue by shamanez** [salesforce/QAConv#3]
I read in the open-review thread and the paper, that you have used [pretrained-ConvSum model](https://github.com/salesforce/ConvSumm/tree/master/CODS#abstract) to generate summaries for conversations. 

Can we have those generated summaries?

I actually checked the ConvSum git and there are two methods to generate summaries, in case if I understood the problem correctly, which model I should use to generate summaries?

**Comment by jasonwu0731** [comment]
@shamanez,

Please follow the guideline in that repo to generate the summary. In this paper, we use `Salesforce/bart-large-xsum-samsum` checkpoints to run through all the conversational chunks.

**Comment by shamanez** [comment]
Thanks.
