### ISSUE TITLE
V1.1 version of data does not have document files

### ISSUE THREAD

**Issue by shashankneocfc** [salesforce/QAConv#4]
Thanks for releasing this dataset.

V1.1 version does not have document files article_segment.json, article_full.json. However, these 2 files are present in V1.0 version. Is it ok to use train/val/test from V1.1 and document files from V1.0 ?

**Comment by jasonwu0731** [comment]
Hi @shashankneocfc 

Yes the article files are the same. I have updated them to be included in both zip files. Thanks.
